### ISSUE TITLE
Første iteration

### ISSUE THREAD

**Issue by n0bis** [n0bis/gruppe9#158]
- [x] Formål
- [x] Kravspecifikation
- [ ] Designalternativer
   - [ ] Konceptuel model
   - [ ] Fysisk design
- [ ] (Prototyper)
- [x] Evaluering
- [x] Sammenfatning af første iteration

**Comment by mdhenriksen** [comment]
Skal der være en evaluering? :dagger:

**Comment by n0bis** [comment]
Der er ikke noget skal have, kun hvis du kan se idén med det 👍
